# Generated by Django 4.0.5 on 2022-06-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='No Name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='0000000000', max_length=10)),
                ('name', models.TextField(default='No Name', max_length=255)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=20)),
                ('email', models.EmailField(default='@no1.com', max_length=254)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managerApp.department')),
            ],
        ),
    ]
