# Generated by Django 4.0.5 on 2022-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='noname@no1.vn', max_length=254),
        ),
    ]
