# Generated by Django 4.0.5 on 2022-06-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0002_alter_staff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeLog', models.DateTimeField()),
                ('isPresent', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managerApp.staff')),
            ],
        ),
    ]
